### PR TITLE
Markxtang patch 1

### PR DESCRIPTION
**Pull request by markxtang**
Replaced logo-icon-color.svg with a new one that doesn't use the mask property. This should make it easier to work with and less prone to issues. Please check the SVG code to make sure it's good. On Figma, the image is 280X210, but the exported SVG shows 280X211. I'm not too sure how to fix this, or whether or not it matters.

### CODE REVIEW

**Comment by kof** [comment]
It does say in in code that its 211px height, it sounds like figma is showing you 210 but exporting 211?

**Comment by markxtang** [comment]
> It does say in in code that its 211px height, it sounds like figma is showing you 210 but exporting 211?

Yup, that is correct. I tried changing the height by tweaking this in notepad: 
`<svg width="280" height="211" viewBox="0 0 280 211" fill="none" xmlns="http://www.w3.org/2000/svg">`
But the result was the logo got slightly cropped off at the bottom.

I also tried editing the svg file in Illustrator, which solved the problem visually, but upon saving, the svg code changed to Illustrators formating (which I remember was not desirable based on previous conversations)

I'll take a look at it again in Figma, maybe there's something I missed.

**Comment by markxtang** [comment]
Just managed to solve the svg export size issue (literally just had to scale it down and back up in Figma). Please check

**Comment by kof** [comment]
Looking good (mergeable)
Not perfect because of some sharp edges on the inner side of the feet, but seems at least to render same way in both safari and chrome

**Review by kof — APPROVED** [review]

**Pull request merged**
